name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v6

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install mdbook
        run: cargo install mdbook --no-default-features --features search --vers "^0.5" --locked

      - name: Install mdbook-gitinfo
        run: cargo install mdbook-gitinfo

      - name: Install mdbook-embedify
        run: cargo install mdbook-embedify

      - name: Build book
        working-directory: .
        run: mdbook build

      - name: Deploy to pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          force_orphan: true